version: '3.3'

# Minio
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
# https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/docker-compose.yaml

# Elasticsearch
# RUN sysctl -w vm.max_map_count=262144 BEFORE RUNNING COMPOSE
# https://github.com/maxyermayank/docker-compose-elasticsearch-kibana
# https://blog.ruanbekker.com/blog/2018/04/29/running-a-3-node-elasticsearch-cluster-with-docker-compose-on-your-laptop-for-testing/
# https://markheath.net/post/exploring-elasticsearch-with-docker

services:

  portainer:
    image: portainer/portainer:latest
    container_name: container_portainer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer:/data
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command:
      ["--admin-password", "${PORTAINER_INITIAL_PASSWORD}"]

  minio1:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_1
    volumes:
    - vol_minio_1:/data
    ports:
    - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio2:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_2
    volumes:
    - vol_minio_2:/data
    ports:
    - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio3:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_3
    volumes:
    - vol_minio_3:/data
    ports:
    - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio4:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_4
    volumes:
    - vol_minio_4:/data
    ports:
    - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
#    container_name: container_elasticsearch
#    environment:
#    - node.name=es01
#    - cluster.name=docker-cluster
#    - bootstrap.memory_lock=true
#    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      nproc: 65535
#      memlock:
#        soft: -1
#        hard: -1
#    cap_add:
#    - ALL
#    privileged: true
#    deploy:
#      mode: global
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
#    volumes:
#    - vol_es:/usr/share/elasticsearch/data
#    ports:
#    - "9200:9200"
#    - "9300:9300"


volumes:
  vol_portainer:
  vol_minio_1:
  vol_minio_2:
  vol_minio_3:
  vol_minio_4:
  vol_es:
