version: '3.3'

services:

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer:/data
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command:
      ["--admin-password", "${PORTAINER_INITIAL_PASSWORD}"]


  minio1:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_1
    volumes:
    - vol_minio_1:/data
    ports:
    - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio2:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_2
    volumes:
    - vol_minio_2:/data
    ports:
    - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio3:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_3
    volumes:
    - vol_minio_3:/data
    ports:
    - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio4:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    container_name: container_minio_4
    volumes:
    - vol_minio_4:/data
    ports:
    - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  master:
    image: gettyimages/spark
    command: >
      sh -c "bin/spark-class org.apache.spark.deploy.master.Master -h master"
    container_name: spark-master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    build:
      context: ./data
    links:
      - elasticsearch
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  worker1:
    image: gettyimages/spark
    command: >
      sh -c "bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077"
    container_name: spark-worker1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    build:
      context: ./spark
    links:
      - master
      - minio1:minio
      - elasticsearch
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data

  worker2:
    image: gettyimages/spark
    command: >
      sh -c "bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077"
    container_name: spark-worker2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: localhost
    build:
      context: ./spark
    links:
      - master
      - minio2:minio
      - elasticsearch
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8882
    ports:
      - 8082:8082
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data

  worker3:
    image: gettyimages/spark
    command: >
      sh -c "bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077"
    container_name: spark-worker3
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8883
      SPARK_WORKER_WEBUI_PORT: 8083
      SPARK_PUBLIC_DNS: localhost
    build:
      context: ./spark
    links:
      - master
      - minio3:minio
      - elasticsearch
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8883
    ports:
      - 8083:8083
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data

  worker4:
    image: gettyimages/spark
    command: >
      sh -c "bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077"
    container_name: spark-worker4
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8884
      SPARK_WORKER_WEBUI_PORT: 8084
      SPARK_PUBLIC_DNS: localhost
    build:
      context: ./spark
    links:
      - master
      - minio4:minio
      - elasticsearch
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8884
    ports:
      - 8084:8084
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - vol_es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
    - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
    - ALL
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  vol_portainer:
  vol_minio_1:
  vol_minio_2:
  vol_minio_3:
  vol_minio_4:
  vol_es:
