version: '3.3'

# RUN sysctl -w vm.max_map_count=262144 BEFORE RUNNING COMPOSE
# SEE https://www.elastic.co/guide/en/elasticsearch/reference/6.0/docker.html FOR MORE DETAILS

# Minio Docker Compose
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml

# TODO test with images in URL below

services:

  portainer:
    image: portainer/portainer:latest
    container_name: container_portainer
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer:/data
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command:
      ["--admin-password", "${PORTAINER_INITIAL_PASSWORD}"]

  minio1:
    image: minio
    container_name: container_minio_1
    volumes:
      - vol_minio_1:/data
    build:
      context: ./minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: 1234
      MINIO_SECRET_KEY: 1234
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data
    # command: minio server /data/minio/

  minio2:
    image: minio
    container_name: container_minio_2
    volumes:
      - vol_minio_2:/data
    build:
      context: ./minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: 1234
      MINIO_SECRET_KEY: 1234
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio3:
    image: minio
    container_name: container_minio_3
    volumes:
      - vol_minio_3:/data
    build:
      context: ./minio
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: 1234
      MINIO_SECRET_KEY: 1234
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data


  minio4:
    image: minio
    container_name: container_minio_4
    volumes:
      - vol_minio_4:/data
    build:
      context: ./minio
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: 1234
      MINIO_SECRET_KEY: 1234
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: container_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - vol_es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - net_es


volumes:
  vol_portainer:
  vol_minio_1:
  vol_minio_2:
  vol_minio_3:
  vol_minio_4:
  vol_es:
    driver: local

networks:
  net_es:
