version: '3.3'

# RUN sysctl -w vm.max_map_count=262144 BEFORE RUNNING COMPOSE
# SEE https://www.elastic.co/guide/en/elasticsearch/reference/6.0/docker.html FOR MORE DETAILS

# Minio Docker Compose
# https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
# https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/docker-compose.yaml
# https://github.com/minio/minio

# TODO test with images in URL below

services:

  portainer:
    image: portainer/portainer:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol_portainer:/data
    ports:
      - "9000:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    command:
      ["--admin-password", "${PORTAINER_INITIAL_PASSWORD}"]

  minio:
    image: minio
    volumes:
      - vol_minio:/data
    build:
      context: ./minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: elfilali
      MINIO_SECRET_KEY: elfilali
    command: minio server /data/minio/


  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    links:
      - "minio"
    build:
      context: ./data
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data


volumes:
  vol_minio:
  vol_portainer:
