#! /bin/sh

cd /home
apt-get update
apt-get install wget
wget https://dl.minio.io/client/mc/release/linux-amd64/mc
chmod +x mc
./mc config host add minio http://minio1:9000 minio minio123 --api "s3v4" --lookup "auto"
./mc mb minio/datas
touch test.txt
./mc cp test.txt minio/datas
